# rysh — try-before-install container image.
#
# Build from the root of this repository:
#
#   docker build -t rysh/rysh .
#   docker run -it --rm rysh/rysh
#
# Work on a repo without installing rysh:
#   docker run -it --rm -v "$PWD:/work" -w /work rysh/rysh
#
# This file is GENERATED by scripts/export-oss.sh from
# scripts/oss-assets/Dockerfile-code in the private repo. Edit it there.
#
# It is deliberately not the private Dockerfile. That one builds the two-module
# monorepo — `COPY rysh-shared/`, built from the monorepo root with
# `-f rysh-cli/Dockerfile`, resolving a `replace ../rysh-shared`. Exported
# verbatim it named a directory this repository does not contain, so
# `docker build .` here failed on the first COPY. This repository is a single
# module that resolves github.com/rysh-ai/rysh-cli-shared from the module proxy
# like any other dependency, so the build is the ordinary one.
#
# ---- build stage -----------------------------------------------------------
FROM golang:1.25-alpine AS build
RUN apk add --no-cache git
WORKDIR /src

# Dependencies first, so edits to the source do not re-download the module graph.
COPY go.mod go.sum ./
RUN go mod download

COPY . .
ENV GOWORK=off CGO_ENABLED=0
RUN go build -ldflags "-s -w" -o /out/rysh ./cmd/rysh

# ---- runtime stage ---------------------------------------------------------
FROM alpine:3.20
# rysh PTY-spawns a shell per pane and embeds a NATS server; ca-certificates for
# provider TLS, git for the agentic git tooling, bash as the default shell.
RUN apk add --no-cache ca-certificates git bash && \
    adduser -D -h /home/rysh rysh
COPY --from=build /out/rysh /usr/local/bin/rysh
USER rysh
WORKDIR /home/rysh
ENV TERM=xterm-256color SHELL=/bin/bash
ENTRYPOINT ["/usr/local/bin/rysh"]
