// SPDX-License-Identifier: Apache-2.0

// Lane and pane-group messages: the two middle levels of the tree. Kept
// together because a pane group only ever exists inside a lane, and the
// operations on them mirror each other.
package msg

import "github.com/rysh-ai/rysh-cli-code/internal/domain"

// ---------------------------------------------------------------------------
// TabActor → LaneActor (rysh.lane.{laneID}.inbox)
// ---------------------------------------------------------------------------

// MsgLaneCreatePaneGroup creates a new pane group in the lane.
//
// GroupID, when set, pre-assigns the new group's ID (normally generated by the
// lane) so the sender can reference the group it asked for — the worktree
// lifecycle (design 008) records which group runs in which worktree at create
// time. WorkingDir, when set, is the directory the group's panes start their
// shells in, overriding the lane's inherited config. Both are carried at birth
// rather than sent as a follow-up MsgSetWorkingDir, which would race the
// group's initial pane creation.
type MsgLaneCreatePaneGroup struct {
	PaneID     string `json:"pane_id"`
	Title      string `json:"title"`
	GroupID    string `json:"group_id,omitempty"`
	WorkingDir string `json:"working_dir,omitempty"`
	// PaneType marks the initial pane as a special variant ("replay" panes
	// never start a shell/PTY). Empty = normal pane. See
	// MsgTabCreatePaneGroupInLane.
	PaneType string `json:"pane_type,omitempty"`

	// Meta is metadata the initial pane is born with. See
	// MsgTabCreatePaneGroupInLane.Meta for why birth rather than a follow-up
	// message.
	Meta map[string]string `json:"meta,omitempty"`
}

// MsgLaneClosePaneGroup closes the active pane group in the lane.
type MsgLaneClosePaneGroup struct{}

// MsgLaneCloseActivePane closes the active (top) pane in the active pane group.
// If the group has only one pane, this is a no-op (use MsgLaneClosePaneGroup instead).
type MsgLaneCloseActivePane struct{}

// MsgLaneFocusGroup moves focus up or down within the lane.
// Replaces MsgLaneFocusGroupUp and MsgLaneFocusGroupDown.
type MsgLaneFocusGroup struct {
	Direction Direction `json:"direction"`
}

// MsgLaneFocusPaneByID makes the pane group containing the given pane the
// active group within the lane, so the lane snapshot reports it as active.
type MsgLaneFocusPaneByID struct {
	ID string `json:"id"`
}

// MsgLaneSetPaneHidden forwards a hide/reveal to the group holding the pane.
type MsgLaneSetPaneHidden struct {
	PaneID string `json:"pane_id"`
	Hidden bool   `json:"hidden"`
}

// MsgLaneCreateStackedPane creates a new stacked pane in the active group.
type MsgLaneCreateStackedPane struct {
	PaneID string `json:"pane_id"`
	Title  string `json:"title"`
}

// MsgLaneStackedPane cycles the stack in the specified direction in the active group.
// Replaces MsgLaneStackedPaneNext and MsgLaneStackedPanePrev.
type MsgLaneStackedPane struct {
	Direction Direction `json:"direction"`
}

// MsgLaneStackedPaneSelect activates the stacked pane at the given 0-based index
// in the active group.
type MsgLaneStackedPaneSelect struct {
	Index int `json:"index"`
}

// MsgLaneStackedPaneMove reorders the active pane within the active group's stack.
type MsgLaneStackedPaneMove struct {
	Direction Direction `json:"direction"`
}

// MsgLaneResizeGroupHeight adjusts the height of the active pane group within the lane.
// Delta > 0 grows the group; Delta < 0 shrinks it.
type MsgLaneResizeGroupHeight struct {
	Delta int `json:"delta"`
}

// MsgLaneEqualizeGroups resets all group rowFlex weights in the lane to equal.
type MsgLaneEqualizeGroups struct{}

// MsgGetLaneSnapshot requests a lane snapshot. When LayoutOnly is set, the
// reply omits heavy per-pane content (output/history/VT) so only structural
// layout fields are carried up the cascade.
type MsgGetLaneSnapshot struct {
	LayoutOnly  bool `json:"layout_only,omitempty"`
	NoHistories bool `json:"no_histories,omitempty"`
}

// MsgLaneSnapshotReply carries the lane snapshot reply.
type MsgLaneSnapshotReply struct {
	Snapshot domain.LaneSnapshot `json:"snapshot"`
}

// MsgGetLaneActivePane requests the active pane ID and pane count from a LaneActor.
type MsgGetLaneActivePane struct{}

// MsgLaneActivePaneReply carries the LaneActor's active pane info.
type MsgLaneActivePaneReply struct {
	PaneID    string `json:"pane_id"`
	PaneCount int    `json:"pane_count"`
}

// ---------------------------------------------------------------------------
// LaneActor → PaneGroupActor (rysh.pane-group.{groupID}.inbox)
// ---------------------------------------------------------------------------

// MsgPaneGroupCreateStackedPane creates a new stacked pane in this group.
type MsgPaneGroupCreateStackedPane struct {
	PaneID string `json:"pane_id"`
	Title  string `json:"title"`
}

// MsgPaneGroupStackedPane cycles the stack in the specified direction.
// Replaces MsgPaneGroupStackedPaneNext and MsgPaneGroupStackedPanePrev.
type MsgPaneGroupStackedPane struct {
	Direction Direction `json:"direction"`
}

// MsgPaneGroupStackedPaneSelect activates the stacked pane at the given 0-based
// index within this group. Out-of-range indices are ignored.
type MsgPaneGroupStackedPaneSelect struct {
	Index int `json:"index"`
}

// MsgPaneGroupFocusPaneByID makes the identified member pane this group's
// active (expanded) stack pane. Sent by the lane's focus-by-id path so the
// GROUP's notion of its active pane follows workspace focus: without it,
// focusing a background stacked pane (mouse click on its title bar, focus
// restore) updated tab/lane bookkeeping only — the group kept the old pane
// expanded while input routed to the newly-"active" invisible one.
type MsgPaneGroupFocusPaneByID struct {
	PaneID string `json:"pane_id"`
}

// MsgPaneGroupSetPaneHidden hides or reveals one pane of this group, moving
// focus off it first when it is the active one (design 027 §5.1).
type MsgPaneGroupSetPaneHidden struct {
	PaneID string `json:"pane_id"`
	Hidden bool   `json:"hidden"`
}

// MsgPaneGroupStackedPaneMove reorders the active pane within this group's stack.
// DirUp moves it toward the front (index 0); DirDown moves it toward the back.
type MsgPaneGroupStackedPaneMove struct {
	Direction Direction `json:"direction"`
}

// ---------------------------------------------------------------------------
// PaneGroup snapshot request/reply
// ---------------------------------------------------------------------------

// MsgGetPaneGroupSnapshot requests a pane group snapshot. When LayoutOnly is
// set, the reply omits heavy per-pane content so only layout fields are carried.
type MsgGetPaneGroupSnapshot struct {
	LayoutOnly  bool `json:"layout_only,omitempty"`
	NoHistories bool `json:"no_histories,omitempty"`
}

// MsgPaneGroupSnapshotReply carries the pane group snapshot reply.
type MsgPaneGroupSnapshotReply struct {
	Snapshot domain.PaneGroupSnapshot `json:"snapshot"`
}

// ---------------------------------------------------------------------------
// PaneGroupActor active-pane query (request/reply on rysh.pane-group.{groupID}.inbox)
// ---------------------------------------------------------------------------

// MsgGetPaneGroupActivePane requests the active pane ID and pane count from a PaneGroupActor.
type MsgGetPaneGroupActivePane struct{}

// MsgPaneGroupActivePaneReply carries the PaneGroupActor's active pane info.
type MsgPaneGroupActivePaneReply struct {
	PaneID    string `json:"pane_id"`
	PaneCount int    `json:"pane_count"`
}

// ---------------------------------------------------------------------------
// CLI → LaneActor (targeted operations)
// ---------------------------------------------------------------------------

// MsgLaneDeletePaneGroup deletes a specific pane group by ID within a lane.
type MsgLaneDeletePaneGroup struct {
	PaneGroupID string `json:"pane_group_id"`
}

// MsgLaneCreateStackedPaneInGroup creates a stacked pane in a specific group.
type MsgLaneCreateStackedPaneInGroup struct {
	PaneGroupID string `json:"pane_group_id"`
	PaneID      string `json:"pane_id"`
	Title       string `json:"title"`
}

// ---------------------------------------------------------------------------
// CLI → PaneGroupActor (targeted operations)
// ---------------------------------------------------------------------------

// MsgPaneGroupDeletePane deletes a specific pane by ID within a group.
type MsgPaneGroupDeletePane struct {
	PaneID string `json:"pane_id"`
}
