package script

import (
	"fmt"
	"strings"
)

// Version is exported to scripts as $RYSH_SCRIPT_VERSION so a script can detect
// what contract it is running under. Bump it when the prelude's observable
// behaviour changes.
const Version = "1"

// Prelude renders the bash that defines RyshFunc and then sources the
// transpiled body.
//
// It is a SEPARATE file that sources the script rather than a header prepended
// to it, and that is load-bearing: prepending would shift every line number, so
// a bash syntax error or `set -x` trace would name a line the author never
// wrote. Sourcing resets $LINENO and $BASH_SOURCE to the sourced file, so
// diagnostics read exactly as if bash had run the .rysh directly. Verified: a
// syntax error on line 5 of the body reports "<name>.rysh: line 5".
//
// The __rysh body has one subtlety worth the comment it carries: `local x=$(…)`
// returns local's status, not the command's. Written that way, every exit code
// in the language would silently be 0 — the single most destructive bug this
// file could have — so the declaration and the assignment are separate
// statements.
func Prelude(bodyPath string) string {
	var b strings.Builder

	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString("# Generated by `rysh script` — do not edit.\n")
	b.WriteString("#\n")
	b.WriteString("# Defines the shell function that ## lines are rewritten into, then sources\n")
	b.WriteString("# the transpiled script. Sourcing (rather than inlining) is what keeps the\n")
	b.WriteString("# script's line numbers identical to the .rysh source.\n")
	b.WriteString("\n")

	// RYSH_OUT / RYSH_STATUS start empty so a script reading them before the
	// first ## command sees the same thing plain bash would.
	b.WriteString("RYSH_OUT=\"\"\n")
	b.WriteString("RYSH_STATUS=0\n")
	b.WriteString("export RYSH_SCRIPT_VERSION=" + Version + "\n")
	b.WriteString("\n")

	fmt.Fprintf(&b, `%s() {
  local __rysh_line
  __rysh_line="$*"
  # Declaration and assignment are separate on purpose: "local x=$(...)" would
  # report local's exit status (always 0) instead of the command's.
  local __rysh_out
  __rysh_out="$("$RYSH_BIN" exec ${RYSH_SESSION:+--session "$RYSH_SESSION"} ${RYSH_TAB:+--tab-id "$RYSH_TAB"} ${RYSH_PANE:+--pane-id "$RYSH_PANE"} -- "$__rysh_line")"
  RYSH_STATUS=$?
  RYSH_OUT="$__rysh_out"
  # Also write to stdout, so pipes and redirects on the ## line behave normally.
  if [ -n "$RYSH_OUT" ]; then printf '%%s\n' "$RYSH_OUT"; fi
  return "$RYSH_STATUS"
}
`, RyshFunc)

	// ##prompt is a script builtin rather than a dispatch-table command,
	// because waiting for an agentic turn inside the WorkspaceActor would
	// freeze the workspace. `rysh prompt` does the waiting from outside.
	fmt.Fprintf(&b, `
%s() {
  local __rysh_text
  __rysh_text="$*"
  local __rysh_out
  # No --quiet: the agent's text goes to stdout so it can be captured into
  # RYSH_OUT, exactly like a ## command's output. Command substitution means it
  # surfaces when the turn ends rather than streaming live — the cost of making
  # the result available to the script.
  __rysh_out="$("$RYSH_BIN" prompt ${RYSH_SESSION:+--session "$RYSH_SESSION"} ${RYSH_PANE:+--pane-id "$RYSH_PANE"} ${RYSH_PROMPT_TIMEOUT:+--timeout "$RYSH_PROMPT_TIMEOUT"} -- "$__rysh_text")"
  RYSH_STATUS=$?
  RYSH_OUT="$__rysh_out"
  if [ -n "$RYSH_OUT" ]; then printf '%%s\n' "$RYSH_OUT"; fi
  return "$RYSH_STATUS"
}
`, PromptFunc)

	b.WriteString("\n")
	fmt.Fprintf(&b, "source %s\n", shellQuote(bodyPath))
	return b.String()
}

// shellQuote renders s as a single-quoted bash word.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
