# Homebrew formula for Rysh — TEMPLATE, NOT THE PUBLISHED FORMULA.
#
# The formula users actually install is generated by GoReleaser and pushed to
# the tap at https://github.com/rysh-ai/homebrew-rysh. This file is a reference
# copy: its PLACEHOLDER_SHA256 values are never filled in here, so it will not
# install as-is.
#
# Its URLs previously pointed at github.com/rysh-ai/rysh — a repository that
# does not exist — which is the same dead-URL class of bug that made every
# advertised install path fail before 2026-07-22. Corrected to packages.rysh.ai
# so that if anyone does copy from this file, they copy something reachable.
#
# Install with:  brew install rysh-ai/rysh/rysh

class Rysh < Formula
  desc "Agentic terminal multiplexer for code development"
  homepage "https://rysh.ai"
  license "MIT"
  version "0.1.0"

  on_macos do
    on_arm do
      url "https://packages.rysh.ai/releases/v#{version}/rysh_darwin_arm64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_DARWIN_ARM64"
    end

    on_intel do
      url "https://packages.rysh.ai/releases/v#{version}/rysh_darwin_amd64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_DARWIN_AMD64"
    end
  end

  on_linux do
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://packages.rysh.ai/releases/v#{version}/rysh_linux_arm64.tar.gz"
        sha256 "PLACEHOLDER_SHA256_LINUX_ARM64"
      end
    end

    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://packages.rysh.ai/releases/v#{version}/rysh_linux_amd64.tar.gz"
        sha256 "PLACEHOLDER_SHA256_LINUX_AMD64"
      end
    end
  end

  def install
    bin.install "rysh"

    # Install example config
    (etc/"rysh").mkpath
    etc.install "rysh.config.example" => "rysh/rysh.config.example"
  end

  def caveats
    <<~EOS
      Rysh is an agentic terminal multiplexer.

      To get started:
        rysh                           # start the default session
        rysh my-project                # start a named session

      Configuration:
        ~/.config/rysh/rysh.config     # user config (TOML)
        #{etc}/rysh/rysh.config.example  # example config

      To enable AI prompts, set your Anthropic API key in rysh.config:
        [provider]
        api_key = "sk-ant-..."

      Or via environment variable:
        export RYSH_API_KEY="sk-ant-..."

      Documentation: https://rysh.ai/docs
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rysh --version 2>&1")
  end
end
